### ISSUE TITLE
Add a background to the app!

### ISSUE THREAD

**Issue by sudipt1999** [sudipt1999/marvelUniverse#1]

**Comment by nidsnitesh** [comment]
I will try this 
please assign me

**Comment by sudipt1999** [comment]
Sure all you need to do is add a background image to  body!

**Comment by ektagarg** [comment]
hey @sudipt1999 
Can you assign it to me? I would like to take this up.

**Comment by sudipt1999** [comment]
sure @ektagarg  go ahead!

**Comment by sudipt1999** [comment]
Both of you can make pr ! I am willing to merge both of them!
