### ISSUE TITLE
Improve pagination UI ! move it to the bottom of the page!

### ISSUE THREAD

**Issue by sudipt1999** [sudipt1999/marvelUniverse#14]

**Comment by troy-johnson** [comment]
I can do this one.

**Comment by sudipt1999** [comment]
Go ahead!

**Comment by troy-johnson** [comment]
![Screen Shot 2019-10-09 at 11 02 16 AM](https://user-images.githubusercontent.com/30636163/66503401-699d2600-ea84-11e9-953a-c636e8784a4c.png)
