### ISSUE TITLE
Improve Loader!

### ISSUE THREAD

**Issue by sudipt1999** [sudipt1999/marvelUniverse#15]
Loader should be related to marver! maybe a moving marve character photo as loader!

**Comment by robertbegna** [comment]
can i work on this?

**Comment by sudipt1999** [comment]
Sure! Go ahead!

**Comment by RaunaqChawhan** [comment]
Is someone working on this or can I proceed on this?

**Comment by sudipt1999** [comment]
!
@RaunaqChawhan  u can work on this!

**Comment by RaunaqChawhan** [comment]
I've improved the default loader with a Captain America shield spinning
