### ISSUE TITLE
Add pagination !

### ISSUE THREAD

**Issue by sudipt1999** [sudipt1999/marvelUniverse#2]
Currently all 800 characters are being loaded at a time !kindly add a pagination!

**Comment by oskar-kupski-elpassion** [comment]
@sudipt1999 Please assign to me

**Comment by sudipt1999** [comment]
Go ahead! There are blog on adding pagination to react ! I guess u could use that!

**Comment by papuruth** [comment]
Done bro

**Comment by sudipt1999** [comment]
@papuruth kindly always comment before starting to work on issue it doesn't creates conflicts with other contributors! Thansk for the pr BTW! Please keep in mind from next time

**Comment by papuruth** [comment]
okay bro

> @papuruth kindly always comment before starting to work on issue it doesn't creates conflicts with other contributors! Thansk for the pr BTW! Please keep in mind from next time

okay bro
