### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by sudipt1999** [sudipt1999/marvelUniverse#3]

**Comment by nidsnitesh** [comment]
I will take care :)
please assign it to me

**Comment by RaunaqChawhan** [comment]
I would like to work on it

**Comment by sudipt1999** [comment]
Sure go ahead! Something's after some other pr being merged are that pagination part need to be improved ! Something based on marvel or similar to it would be really cool! Secondly any improvement u Wana do !

**Comment by RaunaqChawhan** [comment]
I've made changes in the UI. Hope you like it!
#34
