### ISSUE TITLE
Make another page for movies that would display the movie poster or image and have bit info about movie!

### ISSUE THREAD

**Issue by sudipt1999** [sudipt1999/marvelUniverse#4]

**Comment by jpacsai** [comment]
Hi can I work on this issue?

**Comment by sudipt1999** [comment]
Sure !

**Comment by jpacsai** [comment]
The api used for the characters doesn't have a movie endpoint sadly. we can display comics instead of movies maybe?

**Comment by sudipt1999** [comment]
Ya sure! I actually saw avengers character so I thought so!

**Comment by sudipt1999** [comment]
https://github.com/sudipt1999/marvelUniverse/issues/8 issue for single character!

**Comment by jpacsai** [comment]
Oh, I see it's gone :(
